<?php

namespace Anaf\Enums\BalanceSheet;

use Anaf\Contracts\Indicator;

enum OL: string implements Indicator
{
    case PERSONNEL_EFFECTIVE_IN_ECONOMIC_ACTIVITIES = 'EFECTIVUL DE PERSONAL PRIVIND ACTIVITATILE ECONOMICE';
    case PERSONNEL_EFFECTIVE_IN_NON_PROFIT_ACTIVITIES = 'EFECTIVUL DE PERSONAL PRIVIND ACTIVITATEA FARA SCOP PATRIMONIAL';
    case DEFICIT_LOSS = 'DEFICIT/PIERDERE';
    case DEFICIT_LOSS_ANNUAL_PROJECTIONS = 'DEFICIT/PIERDERE - PREVEDERI ANUALE';
    case SURPLUS_PROFIT = 'EXCEDENT/PROFIT';
    case SURPLUS_PROFIT_ANNUAL_PROJECTIONS = 'EXCEDENT/PROFIT - PREVEDERI ANUALE';
    case TOTAL_EXPENSES = 'CHELTUIELI TOTALE';
    case TOTAL_EXPENSES_ANNUAL_PROJECTIONS = 'CHELTUIELI TOTALE - PREVEDERI ANUALE';
    case TOTAL_REVENUE = 'VENITURI TOTALE';
    case TOTAL_REVENUE_ANNUAL_PROJECTIONS = 'VENITURI TOTALE - PREVEDERI ANUALE';
    case LOSS_FROM_ECONOMIC_ACTIVITIES = 'PIERDERE DIN ACTIVITATILE ECONOMICE';
    case LOSS_FROM_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS = 'PIERDERE DIN ACTIVITATILE ECONOMICE - PREVEDERI ANUALE';
    case PROFIT_FROM_ECONOMIC_ACTIVITIES = 'PROFIT DIN ACTIVITATILE ECONOMICE';
    case PROFIT_FROM_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS = 'PROFIT DIN ACTIVITATILE ECONOMICE - PREVEDERI ANUALE';
    case EXPENSES_FOR_ECONOMIC_ACTIVITIES = 'CHELTUIELI PRIVIND ACTIVITATILE ECONOMICE';
    case EXPENSES_FOR_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS = 'CHELTUIELI PRIVIND ACTIVITATILE ECONOMICE - PREVEDERI ANUALE';
    case REVENUE_FROM_ECONOMIC_ACTIVITIES = 'VENITURI DIN ACTIVITATILE ECONOMICE';
    case REVENUE_FROM_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS = 'VENITURI DIN ACTIVITATILE ECONOMICE - PREVEDERI ANUALE';
    case DEFICIT_FROM_SPECIAL_PURPOSE_ACTIVITIES = 'DEFICIT DIN ACTIVITATILE CU DESTINATIE SPECIALA';
    case DEFICIT_FROM_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS = 'DEFICIT DIN ACTIVITATILE CU DESTINATIE SPECIALA - PREVEDERI ANUALE';
    case SURPLUS_FROM_SPECIAL_PURPOSE_ACTIVITIES = 'EXCEDENT DIN ACTIVITATILE CU DESTINATIE SPECIALA';
    case SURPLUS_FROM_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS = 'EXCEDENT DIN ACTIVITATILE CU DESTINATIE SPECIALA - PREVEDERI ANUALE';
    case EXPENSES_FOR_SPECIAL_PURPOSE_ACTIVITIES = 'CHELTUIELI PRIVIND ACTIVITATILE CU DESTINATIE SPECIALA';
    case EXPENSES_FOR_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS = 'CHELTUIELI PRIVIND ACTIVITATILE CU DESTINATIE SPECIALA - PREVEDERI ANUALE';
    case REVENUE_FROM_SPECIAL_PURPOSE_ACTIVITIES = 'VENITURI DIN ACTIVITATILE CU DESTINATIE SPECIALA';
    case REVENUE_FROM_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS = 'VENITURI DIN ACTIVITATILE CU DESTINATIE SPECIALA - PREVEDERI ANUALE';
    case DEFICIT_FROM_NON_PROFIT_ACTIVITIES = 'DEFICIT DIN ACTIVITATILE FARA SCOP PATRIMONIAL';
    case DEFICIT_FROM_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS = 'DEFICIT DIN ACTIVITATILE FARA SCOP PATRIMONIAL - PREVEDERI ANUALE';
    case SURPLUS_FROM_NON_PROFIT_ACTIVITIES = 'EXCEDENT DIN ACTIVITATILE FARA SCOP PATRIMONIAL';
    case SURPLUS_FROM_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS = 'EXCEDENT DIN ACTIVITATILE FARA SCOP PATRIMONIAL - PREVEDERI ANUALE';
    case EXPENSES_FOR_NON_PROFIT_ACTIVITIES = 'CHELTUIELI PRIVIND ACTIVITATILE FARA SCOP PATRIMONIAL';
    case EXPENSES_FOR_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS = 'CHELTUIELI PRIVIND ACTIVITATILE FARA SCOP PATRIMONIAL - PREVEDERI ANUALE';
    case REVENUE_FROM_NON_PROFIT_ACTIVITIES = 'VENITURI DIN ACTIVITATILE FARA SCOP PATRIMONIAL';
    case REVENUE_FROM_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS = 'VENITURI DIN ACTIVITATILE FARA SCOP PATRIMONIAL - PREVEDERI ANUALE';
    case CAPITAL_TOTAL = 'CAPITALURI - TOTAL';
    case FUNDS_FOR_NON_PROFIT_ACTIVITIES = 'FONDURI PRIVIND ACTIVITATILE FARA SCOP PATRIMONIAL';
    case OWN_CAPITAL_TOTAL = 'J. CAPITALURI PROPRII - TOTAL';
    case ADVANCED_REVENUE = 'I. VENITURI IN AVANS';
    case PROVISIONS = 'H. PROVIZIOANE';
    case LIABILITIES_TO_BE_PAID_IN_MORE_THAN_ONE_YEAR = 'G. DATORII CE TREBUIE PLATITE INTR-O PERIOADA MAI MARE DE UN AN';
    case TOTAL_ASSETS_MINUS_CURRENT_LIABILITIES = 'F. TOTAL ACTIVE MINUS DATORII CURENTE';
    case NET_CURRENT_ASSETS_RESPECTIVELY_NET_CURRENT_LIABILITIES = 'E. ACTIVE CIRCULANTE NETE, RESPECTIV DATORII CURENTE NETE';
    case LIABILITIES_TO_BE_PAID_IN_LESS_THAN_ONE_YEAR = 'D. DATORII CE TREBUIE PLATITE INTR-O PERIOADA DE PANA LA UN AN';
    case ADVANCED_EXPENSES = 'C. CHELTUIELI IN AVANS';
    case CURRENT_ASSETS_TOTAL = 'B. ACTIVE CIRCULANTE - TOTAL';
    case FIXED_ASSETS_TOTAL = 'A. ACTIVE IMOBILIZATE - TOTAL';

    public function code(): string
    {
        return match ($this) {
            self::PERSONNEL_EFFECTIVE_IN_ECONOMIC_ACTIVITIES => 'I46',
            self::PERSONNEL_EFFECTIVE_IN_NON_PROFIT_ACTIVITIES => 'I45',
            self::DEFICIT_LOSS => 'I44',
            self::DEFICIT_LOSS_ANNUAL_PROJECTIONS => 'I43',
            self::SURPLUS_PROFIT => 'I42',
            self::SURPLUS_PROFIT_ANNUAL_PROJECTIONS => 'I41',
            self::TOTAL_EXPENSES => 'I40',
            self::TOTAL_EXPENSES_ANNUAL_PROJECTIONS => 'I39',
            self::TOTAL_REVENUE => 'I38',
            self::TOTAL_REVENUE_ANNUAL_PROJECTIONS => 'I37',
            self::LOSS_FROM_ECONOMIC_ACTIVITIES => 'I36',
            self::LOSS_FROM_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS => 'I35',
            self::PROFIT_FROM_ECONOMIC_ACTIVITIES => 'I34',
            self::PROFIT_FROM_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS => 'I33',
            self::EXPENSES_FOR_ECONOMIC_ACTIVITIES => 'I32',
            self::EXPENSES_FOR_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS => 'I31',
            self::REVENUE_FROM_ECONOMIC_ACTIVITIES => 'I30',
            self::REVENUE_FROM_ECONOMIC_ACTIVITIES_ANNUAL_PROJECTIONS => 'I29',
            self::DEFICIT_FROM_SPECIAL_PURPOSE_ACTIVITIES => 'I28',
            self::DEFICIT_FROM_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS => 'I27',
            self::SURPLUS_FROM_SPECIAL_PURPOSE_ACTIVITIES => 'I26',
            self::SURPLUS_FROM_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS => 'I25',
            self::EXPENSES_FOR_SPECIAL_PURPOSE_ACTIVITIES => 'I24',
            self::EXPENSES_FOR_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS => 'I23',
            self::REVENUE_FROM_SPECIAL_PURPOSE_ACTIVITIES => 'I22',
            self::REVENUE_FROM_SPECIAL_PURPOSE_ACTIVITIES_ANNUAL_PROJECTIONS => 'I21',
            self::DEFICIT_FROM_NON_PROFIT_ACTIVITIES => 'I20',
            self::DEFICIT_FROM_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS => 'I19',
            self::SURPLUS_FROM_NON_PROFIT_ACTIVITIES => 'I18',
            self::SURPLUS_FROM_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS => 'I17',
            self::EXPENSES_FOR_NON_PROFIT_ACTIVITIES => 'I16',
            self::EXPENSES_FOR_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS => 'I15',
            self::REVENUE_FROM_NON_PROFIT_ACTIVITIES => 'I14',
            self::REVENUE_FROM_NON_PROFIT_ACTIVITIES_ANNUAL_PROJECTIONS => 'I13',
            self::CAPITAL_TOTAL => 'I12',
            self::FUNDS_FOR_NON_PROFIT_ACTIVITIES => 'I11',
            self::OWN_CAPITAL_TOTAL => 'I10',
            self::ADVANCED_REVENUE => 'I9',
            self::PROVISIONS => 'I8',
            self::LIABILITIES_TO_BE_PAID_IN_MORE_THAN_ONE_YEAR => 'I7',
            self::TOTAL_ASSETS_MINUS_CURRENT_LIABILITIES => 'I6',
            self::NET_CURRENT_ASSETS_RESPECTIVELY_NET_CURRENT_LIABILITIES => 'I5',
            self::LIABILITIES_TO_BE_PAID_IN_LESS_THAN_ONE_YEAR => 'I4',
            self::ADVANCED_EXPENSES => 'I3',
            self::CURRENT_ASSETS_TOTAL => 'I2',
            self::FIXED_ASSETS_TOTAL => 'I1',
        };
    }
}
